/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fypappointment2;

import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javaBean.lecturer;
import javaBean.student;
import javax.swing.JOptionPane;

/**
 *
 * @author KaizoDono
 */
public class adminAdd extends javax.swing.JFrame {

    /**
     * Creates new form adminAdd
     */
    public adminAdd() {
        initComponents();
        combovalue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderGroup = new javax.swing.ButtonGroup();
        bgPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        useridLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        FnameLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        phoneNumLabel = new javax.swing.JLabel();
        LnameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        facultyLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressField = new javax.swing.JTextArea();
        useridField = new javax.swing.JTextField();
        fnameField = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        gender = new javax.swing.JRadioButton();
        gnder2 = new javax.swing.JRadioButton();
        lnameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        facultyBox = new javax.swing.JComboBox<>();
        registerBtn = new javax.swing.JPanel();
        registerLabel = new javax.swing.JLabel();
        superviseLabel = new javax.swing.JLabel();
        superviseBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        bgPanel.setBackground(new java.awt.Color(255, 255, 255));

        titleLabel.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(225, 43, 56));
        titleLabel.setText("Admin Registration");

        useridLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        useridLabel.setText("User ID :");

        usernameLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        usernameLabel.setText("User Name:");

        passwordLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        passwordLabel.setText("Password:");

        FnameLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        FnameLabel.setText("First Name:");

        genderLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        genderLabel.setText("Gender:");

        phoneNumLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        phoneNumLabel.setText("Phone Number:");

        LnameLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        LnameLabel.setText("Last Name:");

        addressLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        addressLabel.setText("Address:");

        emailLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        emailLabel.setText("Email Address:");

        facultyLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        facultyLabel.setText("Faculty:");

        addressField.setColumns(20);
        addressField.setRows(5);
        jScrollPane1.setViewportView(addressField);

        gender.setBackground(new java.awt.Color(255, 255, 255));
        GenderGroup.add(gender);
        gender.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        gender.setText("Male");
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });

        gnder2.setBackground(new java.awt.Color(255, 255, 255));
        GenderGroup.add(gnder2);
        gnder2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        gnder2.setText("Female");
        gnder2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnder2ActionPerformed(evt);
            }
        });

        facultyBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PPIMG", "PPSA" }));
        facultyBox.setToolTipText("");

        registerBtn.setBackground(new java.awt.Color(255, 255, 255));
        registerBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        registerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerBtnMouseExited(evt);
            }
        });

        registerLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        registerLabel.setText("Register");

        javax.swing.GroupLayout registerBtnLayout = new javax.swing.GroupLayout(registerBtn);
        registerBtn.setLayout(registerBtnLayout);
        registerBtnLayout.setHorizontalGroup(
            registerBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerBtnLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(registerLabel)
                .addGap(36, 36, 36))
        );
        registerBtnLayout.setVerticalGroup(
            registerBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        superviseLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        superviseLabel.setText("Superise");

        superviseBox.setToolTipText("");

        javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
        bgPanel.setLayout(bgPanelLayout);
        bgPanelLayout.setHorizontalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameLabel)
                    .addComponent(FnameLabel)
                    .addComponent(genderLabel)
                    .addComponent(phoneNumLabel)
                    .addComponent(addressLabel)
                    .addComponent(useridLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bgPanelLayout.createSequentialGroup()
                                .addComponent(gender)
                                .addGap(18, 18, 18)
                                .addComponent(gnder2)))
                        .addGap(18, 18, 18)
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgPanelLayout.createSequentialGroup()
                                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgPanelLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(LnameLabel))
                                    .addComponent(passwordLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(35, 35, 35)
                                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(bgPanelLayout.createSequentialGroup()
                                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgPanelLayout.createSequentialGroup()
                                        .addComponent(emailLabel)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
                                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(superviseLabel)
                                            .addComponent(facultyLabel))
                                        .addGap(38, 38, 38)))
                                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(facultyBox, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(superviseBox, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(useridField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addGap(261, 261, 261))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
                        .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(303, 303, 303))))
        );
        bgPanelLayout.setVerticalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(titleLabel)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordLabel))
                        .addGap(17, 17, 17)
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LnameLabel))
                        .addGap(19, 19, 19))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(useridLabel)
                            .addComponent(useridField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FnameLabel))
                        .addGap(18, 18, 18)))
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genderLabel)
                            .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(gender)
                                .addComponent(gnder2)))
                        .addGap(18, 18, 18)
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneNumLabel)
                            .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressLabel)))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLabel)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(facultyBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facultyLabel))
                        .addGap(22, 22, 22)
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(superviseLabel)
                            .addComponent(superviseBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        gender.setActionCommand("Male");
    }//GEN-LAST:event_genderActionPerformed

    private void gnder2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnder2ActionPerformed
        gnder2.setActionCommand("Female");
    }//GEN-LAST:event_gnder2ActionPerformed

    private void registerBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnMouseEntered
        // TODO add your handling code here:
        registerBtn.setBackground(new Color(255, 22, 22));
        registerLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_registerBtnMouseEntered

    private void registerBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnMouseExited
        registerBtn.setBackground(Color.WHITE);
        registerLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_registerBtnMouseExited

    private void registerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnMouseClicked
        // TODO add your handling code here:
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/YYYY");
        LocalDate localDate = LocalDate.now();
        String level = "";
        lecturer info = null;
        
        if(useridField.getText().equals("") || usernameField.getText().equals("") ||
           passwordField.getText().equals(""))
        {
            level = "";
        }
        else
        {
            level = "lecturer";
            info = new lecturer(useridField.getText(), usernameField.getText(), passwordField.getText()
                , fnameField.getText(), lnameField.getText(), GenderGroup.getSelection().getActionCommand()
                , addressField.getText(), phoneField.getText(), emailField.getText(), level, dtf.format(localDate)
                , facultyBox.getSelectedItem().toString(), superviseBox.getSelectedItem().toString());
        }

        int i = appointmentsysDAO.registerLecturer(info ,level);
        
        if(i>0)
        {
            JOptionPane.showMessageDialog(null, "Lecturer Added", "Status", JOptionPane.INFORMATION_MESSAGE);
            appointmentsysDAO.veiwUser();
            this.dispose();
        }
    }//GEN-LAST:event_registerBtnMouseClicked

    public void combovalue()
    {
        try
        {      
            ArrayList<student> u = appointmentsysDAO.getStudentList();
            for(int i=0; i<u.size(); i++)
            {
                superviseBox.addItem(u.get(i).getUsername());
            }
            
        }
        catch(ArrayIndexOutOfBoundsException ex)
        {
            System.out.println(ex);
        }
         
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FnameLabel;
    private javax.swing.ButtonGroup GenderGroup;
    private javax.swing.JLabel LnameLabel;
    private javax.swing.JTextArea addressField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JComboBox<String> facultyBox;
    private javax.swing.JLabel facultyLabel;
    private javax.swing.JTextField fnameField;
    private javax.swing.JRadioButton gender;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JRadioButton gnder2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lnameField;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneNumLabel;
    private javax.swing.JPanel registerBtn;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JComboBox<String> superviseBox;
    private javax.swing.JLabel superviseLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField useridField;
    private javax.swing.JLabel useridLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
