/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fypappointment2;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javaBean.appointment;
import javaBean.users;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KaizoDono
 */
public class lectHome extends javax.swing.JFrame implements Info {

    /**
     * Creates new form lectHome
     */
    public lectHome() {
        initComponents();
        tableComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        displayName = new javax.swing.JLabel();
        homeBtn = new javax.swing.JPanel();
        homeLabel = new javax.swing.JLabel();
        homeIcon = new javax.swing.JLabel();
        manageBtn = new javax.swing.JPanel();
        manageLabel = new javax.swing.JLabel();
        manageIcon = new javax.swing.JLabel();
        updateBtn = new javax.swing.JPanel();
        updateLabel = new javax.swing.JLabel();
        updateIcon = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JPanel();
        logoutLabel = new javax.swing.JLabel();
        logoutIcon = new javax.swing.JLabel();
        newsPanel = new javax.swing.JPanel();
        newsTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        appointmentTable = new javax.swing.JTable();
        approveBtn = new javax.swing.JPanel();
        addLabel = new javax.swing.JLabel();
        rejectBtn = new javax.swing.JPanel();
        deleteLabel = new javax.swing.JLabel();
        idDisplay = new javax.swing.JTextField();
        viewBtn = new javax.swing.JPanel();
        addLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayInfo = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgPanel.setBackground(new java.awt.Color(255, 255, 255));

        menuPanel.setBackground(new java.awt.Color(41, 41, 48));

        welcomeLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setText("Welcome");

        displayName.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        displayName.setForeground(new java.awt.Color(255, 255, 255));
        displayName.setText("Welcome");

        homeBtn.setBackground(new java.awt.Color(62, 182, 80));
        homeBtn.setForeground(new java.awt.Color(0, 153, 153));
        homeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeBtnMouseExited(evt);
            }
        });

        homeLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(255, 255, 255));
        homeLabel.setText("Home");

        homeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fypappointment2/icon/003-home.png"))); // NOI18N

        javax.swing.GroupLayout homeBtnLayout = new javax.swing.GroupLayout(homeBtn);
        homeBtn.setLayout(homeBtnLayout);
        homeBtnLayout.setHorizontalGroup(
            homeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeBtnLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(homeLabel)
                .addGap(18, 18, 18)
                .addComponent(homeIcon)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        homeBtnLayout.setVerticalGroup(
            homeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        manageBtn.setBackground(new java.awt.Color(41, 41, 48));
        manageBtn.setForeground(new java.awt.Color(0, 153, 153));
        manageBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageBtnMouseExited(evt);
            }
        });

        manageLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        manageLabel.setForeground(new java.awt.Color(255, 255, 255));
        manageLabel.setText("Schedule");

        manageIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fypappointment2/icon/calendar.png"))); // NOI18N

        javax.swing.GroupLayout manageBtnLayout = new javax.swing.GroupLayout(manageBtn);
        manageBtn.setLayout(manageBtnLayout);
        manageBtnLayout.setHorizontalGroup(
            manageBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(manageLabel)
                .addGap(18, 18, 18)
                .addComponent(manageIcon)
                .addGap(53, 53, 53))
        );
        manageBtnLayout.setVerticalGroup(
            manageBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        updateBtn.setBackground(new java.awt.Color(41, 41, 48));
        updateBtn.setForeground(new java.awt.Color(0, 153, 153));
        updateBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateBtnMouseExited(evt);
            }
        });

        updateLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        updateLabel.setForeground(new java.awt.Color(255, 255, 255));
        updateLabel.setText("Update Account");

        updateIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fypappointment2/icon/002-settings.png"))); // NOI18N

        javax.swing.GroupLayout updateBtnLayout = new javax.swing.GroupLayout(updateBtn);
        updateBtn.setLayout(updateBtnLayout);
        updateBtnLayout.setHorizontalGroup(
            updateBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateBtnLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(updateLabel)
                .addGap(18, 18, 18)
                .addComponent(updateIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        updateBtnLayout.setVerticalGroup(
            updateBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        logoutBtn.setBackground(new java.awt.Color(41, 41, 48));
        logoutBtn.setForeground(new java.awt.Color(0, 153, 153));
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutBtnMouseExited(evt);
            }
        });

        logoutLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutLabel.setText("Logout");

        logoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fypappointment2/icon/005-logout.png"))); // NOI18N

        javax.swing.GroupLayout logoutBtnLayout = new javax.swing.GroupLayout(logoutBtn);
        logoutBtn.setLayout(logoutBtnLayout);
        logoutBtnLayout.setHorizontalGroup(
            logoutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutLabel)
                .addGap(18, 18, 18)
                .addComponent(logoutIcon)
                .addGap(52, 52, 52))
        );
        logoutBtnLayout.setVerticalGroup(
            logoutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logoutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logoutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(welcomeLabel)
                .addGap(31, 31, 31)
                .addComponent(displayName)
                .addContainerGap(13, Short.MAX_VALUE))
            .addComponent(homeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcomeLabel)
                    .addComponent(displayName))
                .addGap(43, 43, 43)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(manageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        newsPanel.setBackground(new java.awt.Color(255, 255, 255));
        newsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));

        newsTitle.setBackground(new java.awt.Color(255, 255, 255));
        newsTitle.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        newsTitle.setText("APPOINTMENT");

        appointmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Student Name", "Subject", "Status"
            }
        ));
        appointmentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appointmentTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(appointmentTable);

        approveBtn.setBackground(new java.awt.Color(62, 182, 80));
        approveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        approveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                approveBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                approveBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                approveBtnMouseExited(evt);
            }
        });

        addLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        addLabel.setForeground(new java.awt.Color(255, 255, 255));
        addLabel.setText("Approve");

        javax.swing.GroupLayout approveBtnLayout = new javax.swing.GroupLayout(approveBtn);
        approveBtn.setLayout(approveBtnLayout);
        approveBtnLayout.setHorizontalGroup(
            approveBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(approveBtnLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(addLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        approveBtnLayout.setVerticalGroup(
            approveBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, approveBtnLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(addLabel)
                .addContainerGap())
        );

        rejectBtn.setBackground(new java.awt.Color(225, 43, 56));
        rejectBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rejectBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rejectBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rejectBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rejectBtnMouseExited(evt);
            }
        });

        deleteLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        deleteLabel.setForeground(new java.awt.Color(255, 255, 255));
        deleteLabel.setText("Reject");

        javax.swing.GroupLayout rejectBtnLayout = new javax.swing.GroupLayout(rejectBtn);
        rejectBtn.setLayout(rejectBtnLayout);
        rejectBtnLayout.setHorizontalGroup(
            rejectBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rejectBtnLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(deleteLabel)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        rejectBtnLayout.setVerticalGroup(
            rejectBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rejectBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteLabel)
                .addContainerGap())
        );

        idDisplay.setEditable(false);
        idDisplay.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        viewBtn.setBackground(new java.awt.Color(62, 182, 80));
        viewBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewBtnMouseExited(evt);
            }
        });

        addLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        addLabel1.setForeground(new java.awt.Color(255, 255, 255));
        addLabel1.setText("View");

        javax.swing.GroupLayout viewBtnLayout = new javax.swing.GroupLayout(viewBtn);
        viewBtn.setLayout(viewBtnLayout);
        viewBtnLayout.setHorizontalGroup(
            viewBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewBtnLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(addLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        viewBtnLayout.setVerticalGroup(
            viewBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewBtnLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(addLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout newsPanelLayout = new javax.swing.GroupLayout(newsPanel);
        newsPanel.setLayout(newsPanelLayout);
        newsPanelLayout.setHorizontalGroup(
            newsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newsPanelLayout.createSequentialGroup()
                .addGroup(newsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newsPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(newsTitle))
                    .addGroup(newsPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(newsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newsPanelLayout.createSequentialGroup()
                                .addComponent(idDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rejectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(approveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        newsPanelLayout.setVerticalGroup(
            newsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newsPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(newsTitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(newsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(rejectBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idDisplay)
                        .addComponent(approveBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        displayInfo.setEditable(false);
        displayInfo.setColumns(20);
        displayInfo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        displayInfo.setRows(5);
        displayInfo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        displayInfo.setEnabled(false);
        jScrollPane1.setViewportView(displayInfo);

        jPanel1.setBackground(new java.awt.Color(62, 182, 80));
        jPanel1.setForeground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lecturer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
        bgPanel.setLayout(bgPanelLayout);
        bgPanelLayout.setHorizontalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addComponent(newsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        bgPanelLayout.setVerticalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 564, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  
    private void tableComponents()
    {
        appointmentTable.getTableHeader().setFont(new Font("Calibri",Font.BOLD, 14));
        appointmentTable.getTableHeader().setOpaque(false);
        appointmentTable.getTableHeader().setBackground(new Color(255, 22, 22));
        appointmentTable.getTableHeader().setForeground(Color.white);
        appointmentTable.setRowHeight(25);
    
    }
    
    public void viewAppt()
    {
        model = (DefaultTableModel) appointmentTable.getModel();
        ArrayList<appointment> a = appointmentsysDAO.getAppt(displayName.getText());
        Object data[] = new Object[4];

        for(int i= 0; i<a.size(); i++)
        {
            data[0] = a.get(i).getAppID();
            data[1] = a.get(i).getStudentid();
            data[2] = a.get(i).getAppSubject();
            data[3] = a.get(i).getAppStatus();
            
            model.addRow(data); 
        }
    }
    
    private void homeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseEntered
        // TODO add your handling code here:
        homeBtn.setBackground(new Color( 62, 182, 80));
        updateBtn.setBackground(new Color( 41, 41, 48));
        manageBtn.setBackground(new Color( 41, 41, 48));
        logoutBtn.setBackground(new Color( 41, 41, 48));
    }//GEN-LAST:event_homeBtnMouseEntered

    private void homeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseExited
        homeBtn.setBackground(new Color( 62, 182, 80));
        updateBtn.setBackground(new Color( 41, 41, 48));
        manageBtn.setBackground(new Color( 41, 41, 48));
        logoutBtn.setBackground(new Color( 41, 41, 48));
    }//GEN-LAST:event_homeBtnMouseExited

    private void manageBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageBtnMouseClicked
        // TODO add your handling code here:
        lectManage goManage = new lectManage();
        goManage.setDisplayName(displayName.getText());
        goManage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manageBtnMouseClicked

    private void manageBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageBtnMouseEntered
        homeBtn.setBackground(new Color( 62, 182, 80));
        updateBtn.setBackground(new Color( 41, 41, 48));
        manageBtn.setBackground(new Color( 62, 182, 80));
        logoutBtn.setBackground(new Color( 41, 41, 48));
    }//GEN-LAST:event_manageBtnMouseEntered

    private void manageBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageBtnMouseExited
        homeBtn.setBackground(new Color( 62, 182, 80));
        updateBtn.setBackground(new Color( 41, 41, 48));
        manageBtn.setBackground(new Color( 41, 41, 48));
        logoutBtn.setBackground(new Color( 41, 41, 48));
    }//GEN-LAST:event_manageBtnMouseExited

    private void updateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseClicked
        // TODO add your handling code here:
        lectUpdate goUpdate = new lectUpdate();
        goUpdate.setDisplayName(displayName.getText());
        goUpdate.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_updateBtnMouseClicked

    private void updateBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseEntered
        homeBtn.setBackground(new Color( 62, 182, 80));
        updateBtn.setBackground(new Color( 62, 182, 80));
        manageBtn.setBackground(new Color( 41, 41, 48));
        logoutBtn.setBackground(new Color( 41, 41, 48));
    }//GEN-LAST:event_updateBtnMouseEntered

    private void updateBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseExited
        homeBtn.setBackground(new Color( 62, 182, 80));
        updateBtn.setBackground(new Color( 41, 41, 48));
        manageBtn.setBackground(new Color( 41, 41, 48));
        logoutBtn.setBackground(new Color( 41, 41, 48));
    }//GEN-LAST:event_updateBtnMouseExited

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        // TODO add your handling code here:
        Login main = new Login();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void logoutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseEntered
        homeBtn.setBackground(new Color(  62, 182, 80));
        updateBtn.setBackground(new Color( 41, 41, 48));
        manageBtn.setBackground(new Color( 41, 41, 48));
        logoutBtn.setBackground(new Color(  62, 182, 80));
    }//GEN-LAST:event_logoutBtnMouseEntered

    private void logoutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseExited
        homeBtn.setBackground(new Color( 62, 182, 80));
        updateBtn.setBackground(new Color( 41, 41, 48));
        manageBtn.setBackground(new Color( 41, 41, 48));
        logoutBtn.setBackground(new Color( 41, 41, 48));
    }//GEN-LAST:event_logoutBtnMouseExited

    private void approveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_approveBtnMouseClicked
        appointmentsysDAO.ApproveAppt(idDisplay.getText());
        model.setRowCount(0);
        viewAppt();
    }//GEN-LAST:event_approveBtnMouseClicked

    private void approveBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_approveBtnMouseEntered
        approveBtn.setBackground(new Color( 5, 124, 23));
    }//GEN-LAST:event_approveBtnMouseEntered

    private void approveBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_approveBtnMouseExited
        approveBtn.setBackground(new Color( 62, 182, 80));
    }//GEN-LAST:event_approveBtnMouseExited

    private void rejectBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rejectBtnMouseClicked
        appointmentsysDAO.RejectAppt(idDisplay.getText());
        model.setRowCount(0);
        viewAppt();
    }//GEN-LAST:event_rejectBtnMouseClicked

    private void rejectBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rejectBtnMouseEntered
        rejectBtn.setBackground(new Color(192, 0, 32));
    }//GEN-LAST:event_rejectBtnMouseEntered

    private void rejectBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rejectBtnMouseExited
        rejectBtn.setBackground(new Color( 225, 43, 56));
    }//GEN-LAST:event_rejectBtnMouseExited

    private void viewBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBtnMouseClicked
        // TODO add your handling code here:
        lectView goView = new lectView();
        goView.viewMail(idDisplay.getText());
        goView.setVisible(true);
    }//GEN-LAST:event_viewBtnMouseClicked

    private void viewBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBtnMouseEntered
        viewBtn.setBackground(new Color( 5, 124, 23));
    }//GEN-LAST:event_viewBtnMouseEntered

    private void viewBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBtnMouseExited
        viewBtn.setBackground(new Color( 62, 182, 80));
    }//GEN-LAST:event_viewBtnMouseExited

    private void appointmentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointmentTableMouseClicked
        int row = appointmentTable.getSelectedRow();
        idDisplay.setText(model.getValueAt(row, 0).toString());
    }//GEN-LAST:event_appointmentTableMouseClicked

    //manual methods
    public void setDisplayName(String name)
    {
        String info = appointmentsysDAO.accountInfo(name);
        int numbers = appointmentsysDAO.numberRegistered();
        displayInfo.setText(info);
        displayName.setText(name);
        viewAppt();
    }
    
    private DefaultTableModel model;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addLabel;
    private javax.swing.JLabel addLabel1;
    private javax.swing.JTable appointmentTable;
    private javax.swing.JPanel approveBtn;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JLabel deleteLabel;
    private javax.swing.JTextArea displayInfo;
    private javax.swing.JLabel displayName;
    private javax.swing.JPanel homeBtn;
    private javax.swing.JLabel homeIcon;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JTextField idDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel logoutBtn;
    private javax.swing.JLabel logoutIcon;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JPanel manageBtn;
    private javax.swing.JLabel manageIcon;
    private javax.swing.JLabel manageLabel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel newsPanel;
    private javax.swing.JLabel newsTitle;
    private javax.swing.JPanel rejectBtn;
    private javax.swing.JPanel updateBtn;
    private javax.swing.JLabel updateIcon;
    private javax.swing.JLabel updateLabel;
    private javax.swing.JPanel viewBtn;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
